"""Valores aprobados en la spec de la iteración 1 (§4.3.7 y §4.3.8), copiados literalmente.

La spec está archivada en docs/historico/iteracion-1/. Si un cambio de datos aprobado
modifica estos valores, se actualizan aquí en la misma tarea.
"""

# (codigo del front, titulo, codigo O*NET)
OCUPACIONES_APROBADAS = {
    ('agricultural-engineer', 'Ingeniero/a agrónomo/a', '17-2021.00'),
    ('architect', 'Arquitecto/a', '17-1011.00'),
    ('biologist', 'Biólogo/a', '19-1029.04'),
    ('civil-engineer', 'Ingeniero/a civil', '17-2051.00'),
    ('community-manager', 'Community manager', '27-3031.00'),
    ('cook', 'Cocinero/a', '35-2014.00'),
    ('data-analyst', 'Analista de datos', '15-2051.00'),
    ('documentary-filmmaker', 'Documentalista', '27-2012.00'),
    ('electrician', 'Electricista', '47-2111.00'),
    ('environmental-engineer', 'Ingeniero/a medioambiental', '17-2081.00'),
    ('event-assistant', 'Asistente de eventos', '39-3031.00'),
    ('event-coordinator', 'Coordinador/a de eventos', '13-1121.00'),
    ('firefighter', 'Bombero/a', '33-2011.00'),
    ('geologist', 'Geólogo/a', '19-2042.00'),
    ('graphic-designer', 'Diseñador/a gráfico/a', '27-1024.00'),
    ('illustrator', 'Ilustrador/a', '27-1013.00'),
    ('journalist', 'Periodista', '27-3023.00'),
    ('lawyer', 'Abogado/a', '23-1011.00'),
    ('logistics-coordinator', 'Coordinador/a logístico/a', '13-1081.00'),
    ('machinery-operator', 'Operador/a de maquinaria', '47-2073.00'),
    ('medical-specialist', 'Médico/a especialista', '29-1216.00'),
    ('meteorologist', 'Meteorólogo/a', '19-2021.00'),
    ('municipal-police', 'Policía municipal', '33-3051.00'),
    ('nurse', 'Enfermero/a', '29-1141.00'),
    ('paramedic', 'Paramédico/a', '29-2043.00'),
    ('photographer', 'Fotógrafo/a', '27-4021.00'),
    ('psychologist', 'Psicólogo/a', '19-3033.00'),
    ('public-administrator', 'Gestor/a público/a', '11-3012.00'),
    ('security-guard', 'Guardia de seguridad', '33-9032.00'),
    ('social-worker', 'Trabajador/a social', '21-1021.00'),
    ('sociologist', 'Sociólogo/a', '19-3041.00'),
    ('sound-technician', 'Técnico/a de sonido', '27-4014.00'),
    ('teacher', 'Docente', '25-2031.00'),
    ('translator', 'Traductor/a', '27-3091.00'),
    ('urban-planner', 'Urbanista', '19-3051.00'),
    ('veterinarian', 'Veterinario/a', '29-1131.00'),
}

# Enunciados por dimensión, en el orden de los ítems (k = 1..10).
ENUNCIADOS_RIASEC = {
    'R': [
        'Reparar una bicicleta o un electrodoméstico.',
        'Armar muebles siguiendo un plano.',
        'Cultivar un huerto o cuidar plantas.',
        'Manejar maquinaria o herramientas eléctricas.',
        'Instalar el cableado eléctrico de una casa.',
        'Construir una maqueta o una estructura de madera.',
        'Cuidar animales en una granja o un refugio.',
        'Trabajar al aire libre, en el campo o en una obra.',
        'Pintar o reparar paredes y techos.',
        'Ensamblar las piezas de una computadora.',
    ],
    'I': [
        'Hacer experimentos en un laboratorio.',
        'Investigar por qué ocurre un fenómeno natural.',
        'Resolver problemas de matemáticas o de lógica.',
        'Analizar datos para encontrar patrones.',
        'Leer sobre descubrimientos científicos.',
        'Estudiar cómo funciona el cuerpo humano.',
        'Observar el cielo y aprender sobre los planetas.',
        'Investigar las causas de una enfermedad.',
        'Programar una solución para un problema.',
        'Comparar información de distintas fuentes antes de concluir.',
    ],
    'A': [
        'Dibujar o pintar.',
        'Escribir cuentos, poemas o guiones.',
        'Tocar un instrumento o componer música.',
        'Actuar en una obra de teatro.',
        'Diseñar un afiche o la portada de una revista.',
        'Tomar fotografías o grabar videos creativos.',
        'Decorar un espacio con un estilo propio.',
        'Bailar o crear una coreografía.',
        'Diseñar ropa o accesorios.',
        'Inventar personajes para una historia o un videojuego.',
    ],
    'S': [
        'Enseñar algo a un niño o a un compañero.',
        'Escuchar y aconsejar a alguien que tiene un problema.',
        'Cuidar a personas enfermas o mayores.',
        'Organizar actividades para ayudar a la comunidad.',
        'Trabajar como voluntario en una campaña.',
        'Explicar un tema difícil a un grupo.',
        'Mediar en una discusión entre amigos.',
        'Acompañar a alguien en su primer día en un lugar nuevo.',
        'Orientar a otros estudiantes sobre sus estudios.',
        'Atender a personas que llegan buscando ayuda.',
    ],
    'E': [
        'Vender un producto o una idea.',
        'Liderar un equipo para cumplir una meta.',
        'Iniciar un negocio propio.',
        'Convencer a otros en un debate.',
        'Organizar un evento y conseguir auspiciadores.',
        'Negociar un acuerdo o un precio.',
        'Representar a tu salón ante la dirección.',
        'Planificar cómo hacer crecer un emprendimiento.',
        'Dirigir una reunión y tomar decisiones.',
        'Promocionar una actividad en redes sociales.',
    ],
    'C': [
        'Ordenar y clasificar documentos.',
        'Llevar las cuentas de ingresos y gastos.',
        'Registrar datos en una hoja de cálculo.',
        'Revisar un texto para corregir errores.',
        'Seguir un procedimiento paso a paso.',
        'Organizar un inventario de materiales.',
        'Preparar un horario o un calendario de actividades.',
        'Archivar información para encontrarla rápido.',
        'Verificar que una factura esté correcta.',
        'Mantener al día una base de datos.',
    ],
}
