from enum import StrEnum


class Rol(StrEnum):
    ESTUDIANTE = "ESTUDIANTE"
    APODERADO = "APODERADO"


class Espacio(StrEnum):
    MISIONES_CAMPO = "MISIONES_CAMPO"
    CIUDAD = "CIUDAD"


class Audiencia(StrEnum):
    ESTUDIANTE = "ESTUDIANTE"
    APODERADO = "APODERADO"


class TipoActividad(StrEnum):
    INFORMATIVA = "INFORMATIVA"
    REGISTRO = "REGISTRO"
    CUESTIONARIO = "CUESTIONARIO"
    CASO = "CASO"


class Visibilidad(StrEnum):
    SIEMPRE = "SIEMPRE"
    AL_DESBLOQUEAR = "AL_DESBLOQUEAR"


class EstadoProgreso(StrEnum):
    EN_CURSO = "EN_CURSO"
    COMPLETADA = "COMPLETADA"


class TipoEventoUso(StrEnum):
    INGRESO = "INGRESO"
    COMPLETA_ACTIVIDAD = "COMPLETA_ACTIVIDAD"
    COMPLETA_BLOQUE = "COMPLETA_BLOQUE"
    RESPUESTA_REFLEXIVA = "RESPUESTA_REFLEXIVA"
    ESCRIBE_ENTRADA_DIARIO = "ESCRIBE_ENTRADA_DIARIO"
    ESCRIBE_ENTRADA_LIBRE = "ESCRIBE_ENTRADA_LIBRE"
    REGISTRA_CHECK_IN = "REGISTRA_CHECK_IN"
    VISTA_CARRERA = "VISTA_CARRERA"
    SUPERA_CASO = "SUPERA_CASO"
    PUBLICA_ENTREVISTA = "PUBLICA_ENTREVISTA"
    ESCRIBE_CARTA = "ESCRIBE_CARTA"
    COMPLETA_CONVERSACION = "COMPLETA_CONVERSACION"
    REINICIA_INSTRUMENTO = "REINICIA_INSTRUMENTO"
    INVITA_A_CREW = "INVITA_A_CREW"
    FORMA_CREW = "FORMA_CREW"
    VENCE_DESAFIO_INTACTO = "VENCE_DESAFIO_INTACTO"


class NivelAjuste(StrEnum):
    BEST_FIT = "BEST_FIT"
    GREAT_FIT = "GREAT_FIT"
    GOOD_FIT = "GOOD_FIT"


class TipoResultado(StrEnum):
    COINCIDENCIAS = "COINCIDENCIAS"
    DESTACADAS = "DESTACADAS"
    COMPARACION = "COMPARACION"


class MomentoAplicacion(StrEnum):
    UNICA = "UNICA"
    ENTRADA = "ENTRADA"
    SALIDA = "SALIDA"


class TipoObjetivo(StrEnum):
    BLOQUE = "BLOQUE"
    ACTIVIDAD = "ACTIVIDAD"
    FICHA = "FICHA"
    TESTIMONIO = "TESTIMONIO"
    PREGUNTA_DIARIO = "PREGUNTA_DIARIO"
    CONVERSACIONES = "CONVERSACIONES"
    INSIGNIA = "INSIGNIA"
    NIVEL = "NIVEL"


class TipoConteo(StrEnum):
    EVENTOS = "EVENTOS"
    REFERENCIAS_DISTINTAS = "REFERENCIAS_DISTINTAS"
    DIAS_DISTINTOS = "DIAS_DISTINTOS"


class OrigenEntrada(StrEnum):
    GUIADA = "GUIADA"
    LIBRE = "LIBRE"


class ClasificacionRespuesta(StrEnum):
    ADECUADA = "ADECUADA"
    VAGA = "VAGA"
    NO_EVALUADA = "NO_EVALUADA"


class EstadoRespuestaRegistro(StrEnum):
    BORRADOR = "BORRADOR"
    PENDIENTE_SEGUIMIENTO = "PENDIENTE_SEGUIMIENTO"
    FINAL = "FINAL"


class OrigenEvaluacion(StrEnum):
    LLM = "LLM"
    RESPALDO_LONGITUD = "RESPALDO_LONGITUD"
